In [1]:
from neo4j import GraphDatabase
import pandas as pd

# Neo4j 连接配置（替换为你的实际信息）
NEO4J_URI = "neo4j+s://32ed3653.databases.neo4j.io"  # Aura 用户用 "neo4j+s://xxx.databases.neo4j.io"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "FEvyWPh7BVdppt5CeW-nBpyYRNd2HhYurBlfrXdoiDo"

# 创建驱动实例
driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))

# 测试连接的函数
def test_connection():
    try:
        with driver.session() as session:
            result = session.run("RETURN 1 AS test")
            return result.single()["test"] == 1
    except Exception as e:
        print(f"连接失败: {e}")
        return False

# 执行测试
if test_connection():
    print("✅ Neo4j 连接成功")
else:
    print("❌ 连接失败，请检查配置")

✅ Neo4j 连接成功

In [20]:

# 执行查询并显示完整结果
df = run_query("""
    MATCH (n)
    RETURN labels(n)[0] AS node_type, count(*) AS count
    ORDER BY count DESC
""")
def run_query(query, params=None):
    with driver.session() as session:
        result = session.run(query, params)
        return pd.DataFrame([dict(record) for record in result])

# 查询所有节点类型（无LIMIT限制）
query = """
MATCH (n)
RETURN labels(n)[0] AS node_type, count(*) AS count
ORDER BY count DESC
"""  # 已移除 LIMIT 10

df = run_query(query)
df.head(13)

      node_type  count
0          item  23231
1   measurement  12449
2   description   3091
3      material   2357
4        period   1697
5          date   1673
6        artist    869
7         donor    649
8       culture    472
9   inscription    133
10         type    118
11     glossary     35
12     category     13